#!/bin/bash

# Set PATH to ensure all necessary commands are available
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

# Log file path
LOG_FILE="$HOME/scripts/bash/auto_commit.log"

# Function to handle commit and push for a vault
commit_and_push() {
    local vault_path=$1
    local vault_name=$(basename "$vault_path")

    {
        echo "[$(date)] Starting auto-commit for $vault_name"
        
        cd "$vault_path" || { echo "[$(date)] Failed to change directory to $vault_path"; exit 1; }

        # Pull the latest changes
        echo "[$(date)] Pulling latest changes for $vault_name"
        git pull origin main

        # Add all changes
        echo "[$(date)] Adding changes for $vault_name"
        git add .

        # Check if there are changes to commit
        if ! git diff-index --quiet HEAD --; then
            # Commit changes with a timestamp message
            echo "[$(date)] Committing changes for $vault_name"
            git commit -m "Auto-commit for $vault_name on $(date)"

            # Push changes to the remote repository
            echo "[$(date)] Pushing changes for $vault_name"
            git push -v origin main
            if [ $? -eq 0 ]; then
                echo "[$(date)] Successfully pushed changes for $vault_name"
            else
                echo "[$(date)] Failed to push changes for $vault_name"
            fi
        else
            echo "[$(date)] No changes to commit in $vault_name"
        fi
    } >> "$LOG_FILE" 2>&1
}

# Commit and push changes for personal
commit_and_push "$HOME/nextcloud/obsidian-vaults/personal/"

# Commit and push changes for work
commit_and_push "$HOME/nextcloud/obsidian-vaults/work"
