# AeroSpace Configuration - Aligned with Sway Config
# Place at ~/.config/aerospace/aerospace.toml

# Startup
after-startup-command = []
start-at-login = true

# Normalizations
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Layouts
accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

# Mouse follows focus
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# Disable macOS hide
automatically-unhide-macos-hidden-apps = true

# Key mapping preset
[key-mapping]
preset = 'colemak'

# Gaps (matching Sway: 4px)
[gaps]
inner.horizontal = 4
inner.vertical = 4
outer.left = 4
outer.bottom = 4
outer.top = 4
outer.right = 4

# Main keybindings
[mode.main.binding]

# Terminal with Ghostty
alt-enter = 'exec-and-forget open -n /Applications/Ghostty.app'

# Browser
alt-b = 'exec-and-forget open -a "Brave Browser"'

# Close window
alt-shift-q = 'close'

# Reload config
alt-shift-c = 'reload-config'

# Fullscreen - removes gaps for true fullscreen feel
# alt-f = 'fullscreen'
# alt-z = 'fullscreen'
alt-z = 'fullscreen --no-outer-gaps'

# Alternative fullscreen with gaps
alt-shift-f = 'fullscreen'

# Floating toggle
alt-t = 'layout floating tiling'

# Layout modes
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# Focus with hjkl
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Focus with arrow keys
alt-left = 'focus left'
alt-down = 'focus down'
alt-up = 'focus up'
alt-right = 'focus right'

# Move windows with hjkl
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Move windows with arrow keys
alt-shift-left = 'move left'
alt-shift-down = 'move down'
alt-shift-up = 'move up'
alt-shift-right = 'move right'

# Resize
alt-minus = 'resize smart -50'
alt-equal = 'resize smart +50'

# Workspaces
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# Move to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# Workspace back-and-forth
alt-tab = 'workspace-back-and-forth'

# Move workspace to monitor
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Modes
alt-r = 'mode resize'
alt-shift-semicolon = 'mode service'

# Resize mode
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
left = 'resize width -50'
down = 'resize height +50'
up = 'resize height -50'
right = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

# Service mode
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']
alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']
