import = [
# uncomment the theme you want below:
# ~/.config/alacritty/catppuccin-latte.toml"
# "~/.config/alacritty/catppuccin-frappe.toml"
# "~/.config/alacritty/catppuccin-macchiato.toml"
# ~/.config/alacritty/catppuccin-mocha.toml"
"~/.config/alacritty/nord.toml"
# "~/.config/alacritty/onenord.toml"
# "~/.config/alacritty/onenord_light.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 14.0

[font.bold]
# LINUX: family = "FiraCode Nerd Font"
# LINUX: family = "MesloLGSDZ Nerd Font"
# BOTH: family = "Fira Code"
# MAC: family = "FiraMono Nerd Font"
# MAC?: family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
# LINUX: family = "FiraCode Nerd Font"
# LINUX: family = "MesloLGSDZ Nerd Font"
# BOTH: family = "Fira Code"
# MAC: family = "FiraMono Nerd Font"
# MAC?: family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
# LINUX: family = "FiraCode Nerd Font"
# LINUX: family = "MesloLGSDZ Nerd Font"
# BOTH: family = "Fira Code"
# MAC: family = "FiraMono Nerd Font"
# MAC?: family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
# LINUX: family = "FiraCode Nerd Font"
# LINUX: family = "MesloLGSDZ Nerd Font"
# BOTH: family = "Fira Code"
# MAC: family = "FiraMono Nerd Font"
# MAC?: family = "FiraCode Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
opacity = 1.0
dynamic_title = true
decorations = "buttonless"
option_as_alt = "Both"
dynamic_padding = false

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
program = "/bin/zsh"

[window.dimensions]
columns = 160
lines = 80

[window.padding]
x = 6
y = 6

