# ~/.config/yazi/yazi.toml
[opener]
# Only define your custom openers - yazi will use defaults for everything else
nvim-lazy = [
  { run = 'NVIM_APPNAME=nvim-lazyvim nvim "$@"', desc = "Open in LazyVim", block = true },
]
video = [{ run = 'mpv "$@"', desc = "Open with mpv" }]
video-fullscreen = [{ run = 'mpv --fullscreen "$@"', desc = "Open fullscreen" }]
video-terminal = [{ run = 'mpv --vo=tct "$@"', desc = "ASCII preview" }]
video-preview = [
  { run = 'mpv --geometry=50% --autofit=50% "$@"', desc = "Preview" },
]
video-audio = [{ run = 'mpv --no-video "$@"', desc = "Audio only" }]
video-playlist = [{ run = 'mpv --playlist-start=1 "$@"', desc = "Play all" }]

[open]
prepend_rules = [
  # Add your video rules BEFORE the defaults
  { mime = "video/*", use = "video" },
  { name = "*.mp4", use = "video" },
  { name = "*.mkv", use = "video" },
  { name = "*.avi", use = "video" },
  { name = "*.mov", use = "video" },
  { name = "*.webm", use = "video" },
  { name = "*.flv", use = "video" },
  { name = "*.m4v", use = "video" },
  { name = "*.mpg", use = "video" },
  { name = "*.mpeg", use = "video" },
  # Optional: override text files to use your custom nvim
  { mime = "text/*", use = "nvim-lazy" },
  { name = "*.txt", use = "nvim-lazy" },
  { name = "*.md", use = "nvim-lazy" },
]
